# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: css.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='css.proto',
  package='melody_cybersim_proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tcss.proto\x12\x15melody_cybersim_proto\x1a\x1bgoogle/protobuf/empty.proto\" \n\x02KV\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x84\x01\n\x0c\x43yberMessage\x12\x1a\n\x12\x64st_application_id\x18\x01 \x02(\t\x12\x1a\n\x12src_application_id\x18\x02 \x02(\t\x12\x10\n\x08msg_type\x18\x03 \x01(\t\x12*\n\x07\x63ontent\x18\x04 \x03(\x0b\x32\x19.melody_cybersim_proto.KV')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_KV = _descriptor.Descriptor(
  name='KV',
  full_name='melody_cybersim_proto.KV',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='melody_cybersim_proto.KV.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='melody_cybersim_proto.KV.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=97,
)


_CYBERMESSAGE = _descriptor.Descriptor(
  name='CyberMessage',
  full_name='melody_cybersim_proto.CyberMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dst_application_id', full_name='melody_cybersim_proto.CyberMessage.dst_application_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_application_id', full_name='melody_cybersim_proto.CyberMessage.src_application_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='melody_cybersim_proto.CyberMessage.msg_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='melody_cybersim_proto.CyberMessage.content', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=232,
)

_CYBERMESSAGE.fields_by_name['content'].message_type = _KV
DESCRIPTOR.message_types_by_name['KV'] = _KV
DESCRIPTOR.message_types_by_name['CyberMessage'] = _CYBERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KV = _reflection.GeneratedProtocolMessageType('KV', (_message.Message,), dict(
  DESCRIPTOR = _KV,
  __module__ = 'css_pb2'
  # @@protoc_insertion_point(class_scope:melody_cybersim_proto.KV)
  ))
_sym_db.RegisterMessage(KV)

CyberMessage = _reflection.GeneratedProtocolMessageType('CyberMessage', (_message.Message,), dict(
  DESCRIPTOR = _CYBERMESSAGE,
  __module__ = 'css_pb2'
  # @@protoc_insertion_point(class_scope:melody_cybersim_proto.CyberMessage)
  ))
_sym_db.RegisterMessage(CyberMessage)


# @@protoc_insertion_point(module_scope)
