
# Error Defines
SUCCESS  = 1
FAILURE = 0
IS_SHARED = 1
BUF_NOT_INITIALIZED = -1
TEMP_ERROR = -2

# Other Defines
PROXY_NODE_ID = 0
CMD_QUIT = 1
MAXPKTSIZE  = 1000
SOCKET_TIMEOUT = 5 
PROXY_UDP_PORT = 5000
POWERSIM_UDP_PORT = 4000